// <auto-generated>
// This file is intentionally excluded from automated linting/formatting.
// Changes to whitespace/layout are deliberate.
// </auto-generated>
#nullable enable
/*
    Centralized dialogs: message prompts, confirmations, and custom modals.
    - Includes read-only passphrase dialog with Copy/Save to %AppData%.
    - Linting/formatting: Do NOT lint or auto-format this file; intentional layout/whitespace.
*/
// TODO[ANCHOR]: DialogService - Passphrase modal with Copy/Save
using System;
using System.IO;
using System.Threading.Tasks;

using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Platform.Storage;
using Avalonia.Threading;

namespace ZTalk.Services
{
    public class DialogService
    {
        public enum UnsavedChangesAction
        {
            Cancel = 0,
            Save = 1,
            Discard = 2
        }

        public enum ToastType
        {
            Info,
            Success,
            Warning,
            Error
        }

        // Lightweight, non-modal info popup that auto-dismisses after a short delay.
        public async Task ShowInfoAsync(string title, string message, int dismissAfterMs = 2500)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Info);
        }

        public async Task ShowInfoAsync(string title, string message, int dismissAfterMs, string? iconText)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
        try { WriteUiLog($"[Toast][Info] Showing: '{title}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                // Play notification sound for legacy info toasts
                _ = Task.Run(async () =>
                {
                    try
                    {
                        if (iconText == "\u26A0" || iconText == "\u274C") // Warning or error icon
                        {
                            await ZTalk.Services.AudioHelper.PlayAlertNotificationAsync();
                        }
                        else
                        {
                            await ZTalk.Services.AudioHelper.PlayNotificationAsync();
                        }
                    }
                    catch (Exception ex)
                    {
                        try { WriteUiLog($"[Toast][Info] Audio notification failed: {ex.Message}"); } catch { }
                    }
                });
                
                var contentPanel = new StackPanel { Spacing = 6 };
                
                // Add title with optional icon
                var titlePanel = new StackPanel 
                { 
                    Orientation = Avalonia.Layout.Orientation.Horizontal, 
                    Spacing = 8 
                };
                
                if (!string.IsNullOrEmpty(iconText))
                {
                    titlePanel.Children.Add(new TextBlock 
                    { 
                        Text = iconText, 
                        FontSize = 16,
                        FontStyle = Avalonia.Media.FontStyle.Normal,
                        FontWeight = Avalonia.Media.FontWeight.Normal,
                        Foreground = new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.FromRgb(255, 165, 0)),
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                        RenderTransform = null // Ensure no transforms are applied
                    });
                }
                
                titlePanel.Children.Add(new TextBlock 
                { 
                    Text = title, 
                    FontWeight = Avalonia.Media.FontWeight.SemiBold,
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                });
                
                contentPanel.Children.Add(titlePanel);
                contentPanel.Children.Add(new TextBlock 
                { 
                    Text = message, 
                    TextWrapping = Avalonia.Media.TextWrapping.Wrap, 
                    MaxWidth = 360 
                });
                
                var border = new Border
                {
                    Padding = new Thickness(12),
                    CornerRadius = new CornerRadius(8),
                    Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Surface"),
                    BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border"),
                    BorderThickness = new Thickness(1),
                    Child = contentPanel
                };

                var toast = new Window
                {
                    CanResize = false,
                    Width = 420,
                    Height = 120,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = null,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    IsHitTestVisible = false,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 32
                };

                try
                {
                    // Position near top-right of owner
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)sz.Width - 440, Math.Max(0, p.Y + 56));
                }
                catch { }

                // Show non-modally, then auto-dismiss
                toast.Show(owner);
                try { await Task.Delay(dismissAfterMs); } catch { }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][Info] Closed: '{title}'"); } catch { }
            });
        }



        // Success info popup with check icon
        public async Task ShowSuccessAsync(string title, string message, int dismissAfterMs = 2500)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Success);
        }

        // Warning info popup with caution icon
        public async Task ShowWarningAsync(string title, string message, int dismissAfterMs = 3000)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Warning);
        }

        // Error info popup with error icon
        public async Task ShowErrorAsync(string title, string message, int dismissAfterMs = 4000)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Error);
        }

        // Enhanced toast with animations, progress, and better styling
        public async Task ShowEnhancedToastAsync(string title, string message, int dismissAfterMs, ToastType type)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
                try { WriteUiLog($"[Toast][{type}] Showing: '{title}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                // Play appropriate sound for toast type
                _ = Task.Run(async () =>
                {
                    try
                    {
                        if (type == ToastType.Warning || type == ToastType.Error)
                        {
                            await ZTalk.Services.AudioHelper.PlayAlertNotificationAsync();
                        }
                        else
                        {
                            await ZTalk.Services.AudioHelper.PlayNotificationAsync();
                        }
                    }
                    catch (Exception ex)
                    {
                        try { WriteUiLog($"[Toast][{type}] Audio notification failed: {ex.Message}"); } catch { }
                    }
                });
                
                // Get type-specific styling
                var (iconText, accentColor, bgColor) = GetToastStyling(type);
                
                var contentPanel = new StackPanel { Spacing = 8 };
                
                // Header with icon and title
                var headerPanel = new StackPanel 
                { 
                    Orientation = Avalonia.Layout.Orientation.Horizontal, 
                    Spacing = 10 
                };
                
                // Icon
                var iconBlock = new TextBlock
                {
                    Text = iconText,
                    FontSize = 18,
                    FontStyle = Avalonia.Media.FontStyle.Normal,
                    FontWeight = Avalonia.Media.FontWeight.Normal,
                    Foreground = new Avalonia.Media.SolidColorBrush(accentColor),
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                    RenderTransform = null
                };
                headerPanel.Children.Add(iconBlock);
                
                // Title
                var titleBlock = new TextBlock
                {
                    Text = title,
                    FontWeight = Avalonia.Media.FontWeight.SemiBold,
                    FontSize = 14,
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                    Foreground = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.PrimaryText")
                };
                headerPanel.Children.Add(titleBlock);
                
                contentPanel.Children.Add(headerPanel);
                
                // Message
                if (!string.IsNullOrWhiteSpace(message))
                {
                    var messageBlock = new TextBlock
                    {
                        Text = message,
                        TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                        MaxWidth = 340,
                        FontSize = 13,
                        Opacity = 0.9,
                        Margin = new Thickness(28, 0, 0, 0), // Indent under icon
                        Foreground = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.SecondaryText")
                    };
                    contentPanel.Children.Add(messageBlock);
                }
                
                // Progress bar
                var progressBar = new Avalonia.Controls.ProgressBar
                {
                    Height = 3,
                    Margin = new Thickness(0, 4, 0, 0),
                    Background = new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.FromArgb(30, 255, 255, 255)),
                    Foreground = new Avalonia.Media.SolidColorBrush(accentColor),
                    Value = 100,
                    Minimum = 0,
                    Maximum = 100
                };
                contentPanel.Children.Add(progressBar);
                
                // Enhanced border with accent and shadow effect
                var border = new Border
                {
                    Padding = new Thickness(16, 12),
                    CornerRadius = new CornerRadius(10),
                    Background = new Avalonia.Media.SolidColorBrush(bgColor),
                    BorderBrush = new Avalonia.Media.SolidColorBrush(accentColor),
                    BorderThickness = new Thickness(0, 0, 0, 3), // Bottom accent line
                    Child = contentPanel,
                    BoxShadow = new Avalonia.Media.BoxShadows(new Avalonia.Media.BoxShadow
                    {
                        Color = Avalonia.Media.Color.FromArgb(40, 0, 0, 0),
                        Blur = 12,
                        OffsetY = 4,
                        OffsetX = 2
                    })
                };
                
                var toast = new Window
                {
                    CanResize = false,
                    SizeToContent = SizeToContent.WidthAndHeight,
                    MinWidth = 300,
                    MaxWidth = 450,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = Avalonia.Media.Brushes.Transparent,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 0
                };
                
                // Click to dismiss
                border.PointerPressed += (_, __) => 
                {
                    try { toast.Close(); } catch { }
                };
                border.Cursor = new Avalonia.Input.Cursor(Avalonia.Input.StandardCursorType.Hand);
                
                // Position in top-right with offset for multiple toasts
                try
                {
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)sz.Width - 470, Math.Max(0, p.Y + 60));
                }
                catch { }
                
                // Smooth fade-in effect
                border.Opacity = 0.2;
                toast.Show(owner);
                
                // Animate opacity from 0.2 to 1.0
                for (int i = 0; i <= 12; i++)
                {
                    border.Opacity = 0.2 + (i * 0.067); // 0.2 to 1.0 in 12 steps
                    await Task.Delay(15); // 180ms total
                }
                
                // Animate progress bar
                var progressAnimation = new System.Threading.CancellationTokenSource();
                _ = Task.Run(async () =>
                {
                    var startTime = DateTime.UtcNow;
                    var duration = dismissAfterMs;
                    
                    while (!progressAnimation.Token.IsCancellationRequested)
                    {
                        var elapsed = (DateTime.UtcNow - startTime).TotalMilliseconds;
                        var remaining = Math.Max(0, duration - elapsed);
                        var progress = Math.Max(0, (remaining / duration) * 100);
                        
                        await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(() =>
                        {
                            try { progressBar.Value = progress; } catch { }
                        });
                        
                        if (remaining <= 0) break;
                        await Task.Delay(50, progressAnimation.Token);
                    }
                }, progressAnimation.Token);
                
                // Auto-dismiss
                try { await Task.Delay(dismissAfterMs); } catch { }
                
                progressAnimation.Cancel();
                
                // Smooth fade-out effect
                for (int i = 10; i >= 0; i--)
                {
                    border.Opacity = i * 0.1; // 1.0 to 0.0 in 11 steps
                    await Task.Delay(20); // 220ms total
                }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][{type}] Closed: '{title}'"); } catch { }
            });
        }
        
        private static (string icon, Avalonia.Media.Color accent, Avalonia.Media.Color bg) GetToastStyling(ToastType type)
        {
            return type switch
            {
                ToastType.Success => ("\u2713", Avalonia.Media.Color.FromRgb(34, 197, 94), Avalonia.Media.Color.FromRgb(240, 253, 244)),   // ✓ Green
                ToastType.Warning => ("\u26A0", Avalonia.Media.Color.FromRgb(245, 158, 11), Avalonia.Media.Color.FromRgb(255, 251, 235)),  // ⚠ Amber
                ToastType.Error => ("\u274C", Avalonia.Media.Color.FromRgb(239, 68, 68), Avalonia.Media.Color.FromRgb(254, 242, 242)),     // ❌ Red
                _ => ("\u2139", Avalonia.Media.Color.FromRgb(59, 130, 246), Avalonia.Media.Color.FromRgb(239, 246, 255))                 // ℹ Blue
            };
        }

        // Centered toast for chat area notifications
        public async Task ShowCenteredToastAsync(string message, int dismissAfterMs = 1500)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
                try { WriteUiLog($"[Toast][Centered] Showing: '{message}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                var border = new Border
                {
                    Padding = new Thickness(16, 8),
                    CornerRadius = new CornerRadius(6),
                    Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Surface"),
                    BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border"),
                    BorderThickness = new Thickness(1),
                    Child = new TextBlock 
                    { 
                        Text = message, 
                        FontWeight = Avalonia.Media.FontWeight.Medium,
                        HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center
                    }
                };

                var toast = new Window
                {
                    CanResize = false,
                    Width = 200,
                    Height = 50,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = null,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    IsHitTestVisible = false,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 32
                };

                try
                {
                    // Position in top-center of owner window
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)(sz.Width - 200) / 2, p.Y + 120);
                }
                catch { }

                // Show non-modally, then auto-dismiss
                toast.Show(owner);
                try { await Task.Delay(dismissAfterMs); } catch { }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][Centered] Closed: '{message}'"); } catch { }
            });

        }

        // Simple text prompt dialog returning edited text or null if cancelled
        public async Task<string?> PromptAsync(string title, string initialText)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return null;

            var tb = new TextBox { Text = initialText, AcceptsReturn = true, TextWrapping = Avalonia.Media.TextWrapping.Wrap, Height = 160 };
            var okBtn = new Button { Content = "Save", IsDefault = true };
            var cancelBtn = new Button { Content = "Cancel", IsCancel = true };
            string? result = null;

            var dialog = new Window
            {
                Title = title,
                // 16:9-ish sizing
                Width = 640,
                Height = 360,
                CanResize = true,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32,
                Content = new StackPanel
                {
                    Margin = new Thickness(16),
                    Spacing = 8,
                    Children =
                    {
                        tb,
                        new StackPanel
                        {
                            Orientation = Avalonia.Layout.Orientation.Horizontal,
                            HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Right,
                            Spacing = 8,
                            Children = { cancelBtn, okBtn }
                        }
                    }
                }
            };
            okBtn.Click += (_, __) => { result = tb.Text ?? string.Empty; dialog.Close(); };
            cancelBtn.Click += (_, __) => { result = null; dialog.Close(); };
            await dialog.ShowDialog(owner);
            return result;
        }

        public async Task<bool> AskContactPermissionAsync(string requesterDisplay, string requesterUid)
        {
            var msg = $"{requesterDisplay} ({requesterUid}) wants to add you as a contact.";
            return await ConfirmAsync("Contact request", msg, "Agree", "Cancel");
        }

        // Warning dialog with triangle caution icon
        public async Task<bool> ConfirmWarningAsync(string title, string message, string confirmText = "OK", string cancelText = "Cancel")
        {
            return await ConfirmAsync(title, message, confirmText, cancelText, "\u26A0");
        }

        // Alert dialog with triangle caution icon (using Unicode triangle with exclamation)
        public async Task<bool> ConfirmAlertAsync(string title, string message, string confirmText = "OK", string cancelText = "Cancel")
        {
            return await ConfirmAsync(title, message, confirmText, cancelText, "\u26A0");
        }

        // Destructive action dialog with triangle caution icon
        public async Task<bool> ConfirmDestructiveAsync(string title, string message, string confirmText = "Delete", string cancelText = "Cancel")
        {
            return await ConfirmAsync(title, message, confirmText, cancelText, "\u26A0");
        }

        public async Task<bool> ConfirmAsync(string title, string message, string confirmText = "OK", string cancelText = "Cancel")
        {
            return await ConfirmAsync(title, message, confirmText, cancelText, null);
        }

        public async Task<bool> ConfirmAsync(string title, string message, string confirmText, string cancelText, string? iconText)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return false;

            var dialog = new Window
            {
                Title = title,
                MinWidth = 420,
                MaxWidth = 600,
                MinHeight = iconText != null ? 200 : 180,
                MaxHeight = 400, // Allow for longer messages
                CanResize = false,
                SizeToContent = SizeToContent.WidthAndHeight,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32
            };

            var cancelBtn = new Button 
            { 
                Content = cancelText, 
                IsDefault = false, 
                IsCancel = true,
                MinWidth = 90,
                Padding = new Avalonia.Thickness(12, 6)
            };
            
            var confirmBtn = new Button 
            { 
                Content = confirmText, 
                IsDefault = true,
                MinWidth = 120,
                Padding = new Avalonia.Thickness(12, 6)
            };

            var grid = new Grid
            {
                RowDefinitions = new RowDefinitions("*,Auto"),
                Margin = new Avalonia.Thickness(20, 16, 20, 16)
            };

            var messagePanel = new StackPanel
            {
                Orientation = Avalonia.Layout.Orientation.Horizontal,
                Spacing = 12,
                VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top,
                Margin = new Avalonia.Thickness(0, 8, 0, 0),
                MaxWidth = 540 // Constrain to fit within dialog margins
            };

            // Add triangle caution icon if provided
            if (!string.IsNullOrEmpty(iconText))
            {
                var iconBlock = new TextBlock
                {
                    Text = iconText,
                    FontSize = 24,
                    FontStyle = Avalonia.Media.FontStyle.Normal,
                    FontWeight = Avalonia.Media.FontWeight.Normal,
                    Foreground = new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.FromRgb(255, 165, 0)), // Orange warning color
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top,
                    Margin = new Avalonia.Thickness(0, 2, 0, 0), // Slight top margin to align with text
                    RenderTransform = null // Ensure no transforms are applied
                };
                messagePanel.Children.Add(iconBlock);
            }

            var messageBlock = new TextBlock 
            { 
                Text = message, 
                TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top,
                MaxWidth = iconText != null ? 480 : 520 // Leave space for icon if present
            };
            messagePanel.Children.Add(messageBlock);
            Grid.SetRow(messagePanel, 0);

            var buttonGrid = new Grid
            {
                ColumnDefinitions = new ColumnDefinitions("Auto,*,Auto"),
                Margin = new Avalonia.Thickness(0, 16, 0, 0)
            };
            Grid.SetRow(buttonGrid, 1);

            Grid.SetColumn(cancelBtn, 0);
            Grid.SetColumn(confirmBtn, 2);
            buttonGrid.Children.Add(cancelBtn);
            buttonGrid.Children.Add(confirmBtn);

            grid.Children.Add(messagePanel);
            grid.Children.Add(buttonGrid);
            dialog.Content = grid;

            bool result = false;
            cancelBtn.Click += (_, __) => { result = false; dialog.Close(); };
            confirmBtn.Click += (_, __) => { result = true; dialog.Close(); };
            
            await dialog.ShowDialog(owner);
            return result;
        }

        // Movable verification modal with a single "Verify" and a "Cancel" button
        public async Task<bool> ShowVerificationDialogAsync(string peerDisplay, string peerUid)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return false;

            var dialog = new Window
            {
                Title = "Verification",
                MinWidth = 460,
                MaxWidth = 600,
                MinHeight = 200,
                MaxHeight = 400,
                CanResize = true,
                SizeToContent = SizeToContent.WidthAndHeight,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32
            };
            var root = new StackPanel { Margin = new Thickness(16), Spacing = 12, MaxWidth = 560 };
            root.Children.Add(new TextBlock { 
                Text = $"You and {peerDisplay} ({peerUid}) will verify each other.", 
                TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                MaxWidth = 520
            });
            var actions = new StackPanel { Orientation = Avalonia.Layout.Orientation.Horizontal, HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Right, Spacing = 8 };
            var cancel = new Button { Content = "Cancel" };
            var verify = new Button { Content = "Verify", IsDefault = true };
            actions.Children.Add(cancel);
            actions.Children.Add(verify);
            root.Children.Add(actions);
            dialog.Content = root;

            bool result = false;
            cancel.Click += (_, __) => { result = false; dialog.Close(); };
            verify.Click += (_, __) => { result = true; dialog.Close(); };
            await dialog.ShowDialog(owner);
            return result;
        }

        public async Task<UnsavedChangesAction> PromptUnsavedChangesAsync(
            string title = "Close Settings",
            string message = "You have unsaved changes. What would you like to do?",
            string saveText = "Save Changes",
            string discardText = "Discard",
            string cancelText = "Cancel")
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner)
            {
                return UnsavedChangesAction.Cancel;
            }

            // Chrome-styled modal window using app theme resources.
            var dialog = new Window
            {
                Title = title,
                MinWidth = 480,
                MaxWidth = 600,
                MinHeight = 220,
                MaxHeight = 350,
                CanResize = false,
                SizeToContent = SizeToContent.WidthAndHeight,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32
            };
            dialog.Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Background");
            dialog.Foreground = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.ForegroundPrimary");

            var rootBorder = new Border
            {
                Padding = new Thickness(12),
                BorderThickness = new Thickness(1)
            };
            rootBorder.Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Background");
            rootBorder.BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border");

            var root = new Grid
            {
                RowDefinitions = new RowDefinitions("Auto, *, Auto")
            };

            var header = new Border
            {
                BorderThickness = new Thickness(0, 0, 0, 1),
                Padding = new Thickness(4, 2, 4, 6)
            };
            header.BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border");
            header.Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Background");
            header.Child = new TextBlock
            {
                Text = title,
                FontWeight = Avalonia.Media.FontWeight.SemiBold
            };
            Grid.SetRow(header, 0);

            var contentPanel = new StackPanel
            {
                Spacing = 8
            };
            
            // Add message with warning icon for unsaved changes
            var messagePanel = new StackPanel
            {
                Orientation = Avalonia.Layout.Orientation.Horizontal,
                Spacing = 12
            };
            
            var warningIcon = new TextBlock
            {
                Text = "\u26A0", // Triangle warning symbol
                FontSize = 20,
                FontStyle = Avalonia.Media.FontStyle.Normal,
                FontWeight = Avalonia.Media.FontWeight.Normal,
                Foreground = new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.FromRgb(255, 165, 0)), // Orange warning color
                VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top,
                Margin = new Avalonia.Thickness(0, 2, 0, 0),
                RenderTransform = null // Ensure no transforms are applied
            };
            
            var messageText = new TextBlock
            {
                Text = message,
                TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                MaxWidth = 480 // Leave space for icon
            };
            
            messagePanel.Children.Add(warningIcon);
            messagePanel.Children.Add(messageText);
            contentPanel.Children.Add(messagePanel);
            Grid.SetRow(contentPanel, 1);

            // Actions: Save (left), Discard (right). Cancel is not shown; Esc acts as Cancel.
            var actionsGrid = new Grid
            {
                ColumnDefinitions = new ColumnDefinitions("Auto, *, Auto"),
                Margin = new Thickness(0, 8, 0, 0)
            };
            var saveBtn = new Button
            {
                Content = saveText,
                IsDefault = true,
                MinWidth = 120,
                Padding = new Thickness(10, 6)
            };
            var discardBtn = new Button
            {
                Content = discardText,
                MinWidth = 120,
                Padding = new Thickness(10, 6)
            };
            Grid.SetColumn(saveBtn, 0);
            Grid.SetColumn(discardBtn, 2);
            actionsGrid.Children.Add(saveBtn);
            actionsGrid.Children.Add(discardBtn);
            Grid.SetRow(actionsGrid, 2);

            root.Children.Add(header);
            root.Children.Add(contentPanel);
            root.Children.Add(actionsGrid);
            rootBorder.Child = root;
            dialog.Content = rootBorder;

            var result = UnsavedChangesAction.Cancel;
            saveBtn.Click += (_, __) =>
            {
                result = UnsavedChangesAction.Save;
                dialog.Close();
            };
            discardBtn.Click += (_, __) =>
            {
                result = UnsavedChangesAction.Discard;
                dialog.Close();
            };

            // Accessibility: Esc = Cancel; Tab order default works via visual tree order.
            dialog.KeyDown += (_, e) =>
            {
                try
                {
                    if (e.Key == Avalonia.Input.Key.Escape)
                    {
                        result = UnsavedChangesAction.Cancel;
                        dialog.Close();
                    }
                }
                catch
                {
                }
            };

            // Log UI change
            try
            {
                WriteUiLog("[Dialog] UnsavedChanges chrome-styled; Save left, Discard right; Cancel removed (Esc supported)");
            }
            catch
            {
            }

            await dialog.ShowDialog(owner);
            return result;
        }

        private static void WriteUiLog(string line)
        {
            try
            {
                if (ZTalk.Utilities.LoggingPaths.Enabled)
                    System.IO.File.AppendAllText(ZTalk.Utilities.LoggingPaths.UI, $"{DateTime.Now:O} {line}{Environment.NewLine}");
            }
            catch { }
        }

        public async Task ShowPassphraseDialogAsync(string passphrase)
        {
            var lifetime = Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            var tb = new TextBox
            {
                Text = passphrase,
                IsReadOnly = true,
                FontFamily = new Avalonia.Media.FontFamily("Consolas"),
            };
            ToolTip.SetTip(tb, "Store this passphrase securely. Anyone with it can access your account.");

            var copyBtn = new Button { Content = "Copy" };
            var saveBtn = new Button { Content = "Save" };
            var okBtn = new Button { Content = "Done", IsDefault = true };

            var dialog = new Window
            {
                Title = "Your account passphrase",
                MinWidth = 540,
                MaxWidth = 700,
                MinHeight = 300,
                MaxHeight = 450,
                CanResize = false,
                SizeToContent = SizeToContent.WidthAndHeight,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32,
                Content = new StackPanel
                {
                    Margin = new Thickness(16),
                    Spacing = 8,
                    MaxWidth = 650,
                    Children =
                    {
                        new TextBlock { 
                            Text = "Write down or save this passphrase now. It cannot be recovered if lost.", 
                            TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                            MaxWidth = 600
                        },
                        tb,
                        new StackPanel
                        {
                            Orientation = Avalonia.Layout.Orientation.Horizontal,
                            HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Right,
                            Spacing = 8,
                            Children = { copyBtn, saveBtn, okBtn }
                        }
                    }
                }
            };

            copyBtn.Click += async (_, __) =>
            {
                try { await dialog.Clipboard!.SetTextAsync(passphrase); }
                catch { }
            };

            saveBtn.Click += async (_, __) =>
            {
                try
                {
                    var dir = ZTalk.Utilities.AppDataPaths.Root;
                    Directory.CreateDirectory(dir);
                    IStorageFolder? start = null;
                    try { start = await dialog.StorageProvider.TryGetFolderFromPathAsync(dir); } catch { }
                    var file = await dialog.StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
                    {
                        Title = "Save passphrase",
                        SuggestedStartLocation = start,
                        SuggestedFileName = "passphrase.txt",
                        FileTypeChoices = new[] { new FilePickerFileType("Text Files") { Patterns = new[] { "*.txt" } } }
                    });
                    if (file != null)
                    {
                        await using var stream = await file.OpenWriteAsync();
                        await using var writer = new StreamWriter(stream);
                        await writer.WriteAsync(passphrase);
                        await writer.FlushAsync();
                    }
                }
                catch { }
            };

            okBtn.Click += (_, __) => dialog.Close();

            await dialog.ShowDialog(owner);
        }
    }
}
