// <auto-generated>
// This file is intentionally excluded from automated linting/formatting.
// Changes to whitespace/layout are deliberate.
// </auto-generated>
#nullable enable
/*
    Centralized dialogs: message prompts, confirmations, and custom modals.
    - Includes read-only passphrase dialog with Copy/Save to %AppData%.
    - Linting/formatting: Do NOT lint or auto-format this file; intentional layout/whitespace.
*/
// TODO[ANCHOR]: DialogService - Passphrase modal with Copy/Save
using System;
using System.IO;
using System.Threading.Tasks;

using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Platform.Storage;

namespace ZTalk.Services
{
    public class DialogService
    {
        public enum UnsavedChangesAction
        {
            Cancel = 0,
            Save = 1,
            Discard = 2
        }

        // Lightweight, non-modal info popup that auto-dismisses after a short delay.
    public async Task ShowInfoAsync(string title, string message, int dismissAfterMs = 2500)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
        try { WriteUiLog($"[Toast][Info] Showing: '{title}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                var border = new Border
                {
                    Padding = new Thickness(12),
                    CornerRadius = new CornerRadius(8),
                    Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Surface"),
                    BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border"),
                    BorderThickness = new Thickness(1),
                    Child = new StackPanel
                    {
                        Spacing = 6,
                        Children =
                        {
                            new TextBlock { Text = title, FontWeight = Avalonia.Media.FontWeight.SemiBold },
                            new TextBlock { Text = message, TextWrapping = Avalonia.Media.TextWrapping.Wrap, MaxWidth = 360 }
                        }
                    }
                };

                var toast = new Window
                {
                    CanResize = false,
                    Width = 420,
                    Height = 120,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = null,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    IsHitTestVisible = false,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 32
                };

                try
                {
                    // Position near top-right of owner
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)sz.Width - 440, Math.Max(0, p.Y + 56));
                }
                catch { }

                // Show non-modally, then auto-dismiss
                toast.Show(owner);
                try { await Task.Delay(dismissAfterMs); } catch { }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][Info] Closed: '{title}'"); } catch { }
            });
        }

        // Centered toast for chat area notifications
        public async Task ShowCenteredToastAsync(string message, int dismissAfterMs = 1500)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
                try { WriteUiLog($"[Toast][Centered] Showing: '{message}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                var border = new Border
                {
                    Padding = new Thickness(16, 8),
                    CornerRadius = new CornerRadius(6),
                    Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Surface"),
                    BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border"),
                    BorderThickness = new Thickness(1),
                    Child = new TextBlock 
                    { 
                        Text = message, 
                        FontWeight = Avalonia.Media.FontWeight.Medium,
                        HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center
                    }
                };

                var toast = new Window
                {
                    CanResize = false,
                    Width = 200,
                    Height = 50,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = null,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    IsHitTestVisible = false,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 32
                };

                try
                {
                    // Position in top-center of owner window
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)(sz.Width - 200) / 2, p.Y + 120);
                }
                catch { }

                // Show non-modally, then auto-dismiss
                toast.Show(owner);
                try { await Task.Delay(dismissAfterMs); } catch { }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][Centered] Closed: '{message}'"); } catch { }
            });

        }

        // Simple text prompt dialog returning edited text or null if cancelled
        public async Task<string?> PromptAsync(string title, string initialText)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return null;

            var tb = new TextBox { Text = initialText, AcceptsReturn = true, TextWrapping = Avalonia.Media.TextWrapping.Wrap, Height = 160 };
            var okBtn = new Button { Content = "Save", IsDefault = true };
            var cancelBtn = new Button { Content = "Cancel", IsCancel = true };
            string? result = null;

            var dialog = new Window
            {
                Title = title,
                // 16:9-ish sizing
                Width = 640,
                Height = 360,
                CanResize = true,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32,
                Content = new StackPanel
                {
                    Margin = new Thickness(16),
                    Spacing = 8,
                    Children =
                    {
                        tb,
                        new StackPanel
                        {
                            Orientation = Avalonia.Layout.Orientation.Horizontal,
                            HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Right,
                            Spacing = 8,
                            Children = { cancelBtn, okBtn }
                        }
                    }
                }
            };
            okBtn.Click += (_, __) => { result = tb.Text ?? string.Empty; dialog.Close(); };
            cancelBtn.Click += (_, __) => { result = null; dialog.Close(); };
            await dialog.ShowDialog(owner);
            return result;
        }

        public async Task<bool> AskContactPermissionAsync(string requesterDisplay, string requesterUid)
        {
            var msg = $"{requesterDisplay} ({requesterUid}) wants to add you as a contact.";
            return await ConfirmAsync("Contact request", msg, "Agree", "Cancel");
        }

        public async Task<bool> ConfirmAsync(string title, string message, string confirmText = "OK", string cancelText = "Cancel")
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return false;

            var dialog = new Window
            {
                Title = title,
                Width = 420,
                Height = 180,
                CanResize = false,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32
            };

            var cancelBtn = new Button 
            { 
                Content = cancelText, 
                IsDefault = false, 
                IsCancel = true,
                MinWidth = 90,
                Padding = new Avalonia.Thickness(12, 6)
            };
            
            var confirmBtn = new Button 
            { 
                Content = confirmText, 
                IsDefault = true,
                MinWidth = 120,
                Padding = new Avalonia.Thickness(12, 6)
            };

            var grid = new Grid
            {
                RowDefinitions = new RowDefinitions("*,Auto"),
                Margin = new Avalonia.Thickness(20, 16, 20, 16)
            };

            var messageBlock = new TextBlock 
            { 
                Text = message, 
                TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                VerticalAlignment = Avalonia.Layout.VerticalAlignment.Top,
                Margin = new Avalonia.Thickness(0, 8, 0, 0)
            };
            Grid.SetRow(messageBlock, 0);

            var buttonGrid = new Grid
            {
                ColumnDefinitions = new ColumnDefinitions("Auto,*,Auto"),
                Margin = new Avalonia.Thickness(0, 16, 0, 0)
            };
            Grid.SetRow(buttonGrid, 1);

            Grid.SetColumn(cancelBtn, 0);
            Grid.SetColumn(confirmBtn, 2);
            buttonGrid.Children.Add(cancelBtn);
            buttonGrid.Children.Add(confirmBtn);

            grid.Children.Add(messageBlock);
            grid.Children.Add(buttonGrid);
            dialog.Content = grid;

            bool result = false;
            cancelBtn.Click += (_, __) => { result = false; dialog.Close(); };
            confirmBtn.Click += (_, __) => { result = true; dialog.Close(); };
            
            await dialog.ShowDialog(owner);
            return result;
        }

        // Movable verification modal with a single "Verify" and a "Cancel" button
        public async Task<bool> ShowVerificationDialogAsync(string peerDisplay, string peerUid)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return false;

            var dialog = new Window
            {
                Title = "Verification",
                // 16:9-ish sizing
                Width = 560,
                Height = 315,
                CanResize = true,
                SizeToContent = SizeToContent.Manual,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32
            };
            var root = new StackPanel { Margin = new Thickness(16), Spacing = 12 };
            root.Children.Add(new TextBlock { Text = $"You and {peerDisplay} ({peerUid}) will verify each other.", TextWrapping = Avalonia.Media.TextWrapping.Wrap });
            var actions = new StackPanel { Orientation = Avalonia.Layout.Orientation.Horizontal, HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Right, Spacing = 8 };
            var cancel = new Button { Content = "Cancel" };
            var verify = new Button { Content = "Verify", IsDefault = true };
            actions.Children.Add(cancel);
            actions.Children.Add(verify);
            root.Children.Add(actions);
            dialog.Content = root;

            bool result = false;
            cancel.Click += (_, __) => { result = false; dialog.Close(); };
            verify.Click += (_, __) => { result = true; dialog.Close(); };
            await dialog.ShowDialog(owner);
            return result;
        }

        public async Task<UnsavedChangesAction> PromptUnsavedChangesAsync(
            string title = "Close Settings",
            string message = "You have unsaved changes. What would you like to do?",
            string saveText = "Save Changes",
            string discardText = "Discard",
            string cancelText = "Cancel")
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner)
            {
                return UnsavedChangesAction.Cancel;
            }

            // Chrome-styled modal window using app theme resources.
            var dialog = new Window
            {
                Title = title,
                Width = 480,
                Height = 220,
                CanResize = false,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32
            };
            dialog.Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Background");
            dialog.Foreground = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.ForegroundPrimary");

            var rootBorder = new Border
            {
                Padding = new Thickness(12),
                BorderThickness = new Thickness(1)
            };
            rootBorder.Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Background");
            rootBorder.BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border");

            var root = new Grid
            {
                RowDefinitions = new RowDefinitions("Auto, *, Auto")
            };

            var header = new Border
            {
                BorderThickness = new Thickness(0, 0, 0, 1),
                Padding = new Thickness(4, 2, 4, 6)
            };
            header.BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border");
            header.Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Background");
            header.Child = new TextBlock
            {
                Text = title,
                FontWeight = Avalonia.Media.FontWeight.SemiBold
            };
            Grid.SetRow(header, 0);

            var contentPanel = new StackPanel
            {
                Spacing = 8
            };
            contentPanel.Children.Add(new TextBlock
            {
                Text = message,
                TextWrapping = Avalonia.Media.TextWrapping.Wrap
            });
            Grid.SetRow(contentPanel, 1);

            // Actions: Save (left), Discard (right). Cancel is not shown; Esc acts as Cancel.
            var actionsGrid = new Grid
            {
                ColumnDefinitions = new ColumnDefinitions("Auto, *, Auto"),
                Margin = new Thickness(0, 8, 0, 0)
            };
            var saveBtn = new Button
            {
                Content = saveText,
                IsDefault = true,
                MinWidth = 120,
                Padding = new Thickness(10, 6)
            };
            var discardBtn = new Button
            {
                Content = discardText,
                MinWidth = 120,
                Padding = new Thickness(10, 6)
            };
            Grid.SetColumn(saveBtn, 0);
            Grid.SetColumn(discardBtn, 2);
            actionsGrid.Children.Add(saveBtn);
            actionsGrid.Children.Add(discardBtn);
            Grid.SetRow(actionsGrid, 2);

            root.Children.Add(header);
            root.Children.Add(contentPanel);
            root.Children.Add(actionsGrid);
            rootBorder.Child = root;
            dialog.Content = rootBorder;

            var result = UnsavedChangesAction.Cancel;
            saveBtn.Click += (_, __) =>
            {
                result = UnsavedChangesAction.Save;
                dialog.Close();
            };
            discardBtn.Click += (_, __) =>
            {
                result = UnsavedChangesAction.Discard;
                dialog.Close();
            };

            // Accessibility: Esc = Cancel; Tab order default works via visual tree order.
            dialog.KeyDown += (_, e) =>
            {
                try
                {
                    if (e.Key == Avalonia.Input.Key.Escape)
                    {
                        result = UnsavedChangesAction.Cancel;
                        dialog.Close();
                    }
                }
                catch
                {
                }
            };

            // Log UI change
            try
            {
                WriteUiLog("[Dialog] UnsavedChanges chrome-styled; Save left, Discard right; Cancel removed (Esc supported)");
            }
            catch
            {
            }

            await dialog.ShowDialog(owner);
            return result;
        }

        private static void WriteUiLog(string line)
        {
            try
            {
                if (ZTalk.Utilities.LoggingPaths.Enabled)
                    System.IO.File.AppendAllText(ZTalk.Utilities.LoggingPaths.UI, $"{DateTime.Now:O} {line}{Environment.NewLine}");
            }
            catch { }
        }

        public async Task ShowPassphraseDialogAsync(string passphrase)
        {
            var lifetime = Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            var tb = new TextBox
            {
                Text = passphrase,
                IsReadOnly = true,
                FontFamily = new Avalonia.Media.FontFamily("Consolas"),
            };
            ToolTip.SetTip(tb, "Store this passphrase securely. Anyone with it can access your account.");

            var copyBtn = new Button { Content = "Copy" };
            var saveBtn = new Button { Content = "Save" };
            var okBtn = new Button { Content = "Done", IsDefault = true };

            var dialog = new Window
            {
                Title = "Your account passphrase",
                // 16:9-ish sizing
                Width = 640,
                Height = 360,
                CanResize = false,
                WindowStartupLocation = WindowStartupLocation.CenterOwner,
                ExtendClientAreaToDecorationsHint = true,
                ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                ExtendClientAreaTitleBarHeightHint = 32,
                Content = new StackPanel
                {
                    Margin = new Thickness(16),
                    Spacing = 8,
                    Children =
                    {
                        new TextBlock { Text = "Write down or save this passphrase now. It cannot be recovered if lost.", TextWrapping = Avalonia.Media.TextWrapping.Wrap },
                        tb,
                        new StackPanel
                        {
                            Orientation = Avalonia.Layout.Orientation.Horizontal,
                            HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Right,
                            Spacing = 8,
                            Children = { copyBtn, saveBtn, okBtn }
                        }
                    }
                }
            };

            copyBtn.Click += async (_, __) =>
            {
                try { await dialog.Clipboard!.SetTextAsync(passphrase); }
                catch { }
            };

            saveBtn.Click += async (_, __) =>
            {
                try
                {
                    var dir = ZTalk.Utilities.AppDataPaths.Root;
                    Directory.CreateDirectory(dir);
                    IStorageFolder? start = null;
                    try { start = await dialog.StorageProvider.TryGetFolderFromPathAsync(dir); } catch { }
                    var file = await dialog.StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
                    {
                        Title = "Save passphrase",
                        SuggestedStartLocation = start,
                        SuggestedFileName = "passphrase.txt",
                        FileTypeChoices = new[] { new FilePickerFileType("Text Files") { Patterns = new[] { "*.txt" } } }
                    });
                    if (file != null)
                    {
                        await using var stream = await file.OpenWriteAsync();
                        await using var writer = new StreamWriter(stream);
                        await writer.WriteAsync(passphrase);
                        await writer.FlushAsync();
                    }
                }
                catch { }
            };

            okBtn.Click += (_, __) => dialog.Close();

            await dialog.ShowDialog(owner);
        }
    }
}
