// <auto-generated>
// This file is intentionally excluded from automated linting/formatting.
// Changes to whitespace/layout are deliberate.
// </auto-generated>
#nullable enable
/*
    Centralized dialogs: message prompts, confirmations, and custom modals.
    - Includes read-only passphrase dialog with Copy/Save to %AppData%.
    - Linting/formatting: Do NOT lint or auto-format this file; intentional layout/whitespace.
*/
// TODO[ANCHOR]: DialogService - Passphrase modal with Copy/Save
using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Platform.Storage;
using Avalonia.Threading;

using Zer0Talk.Utilities;

namespace Zer0Talk.Services
{
    public partial class DialogService
    {
        public enum UnsavedChangesAction
        {
            Cancel = 0,
            Save = 1,
            Discard = 2
        }

        public enum ToastType
        {
            Info,
            Success,
            Warning,
            Error
        }

        // Lightweight, non-modal info popup that auto-dismisses after a short delay.
        public async Task ShowInfoAsync(string title, string message, int dismissAfterMs = 2500)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Info);
        }

        public async Task ShowInfoAsync(string title, string message, int dismissAfterMs, string? iconText)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
        try { WriteUiLog($"[Toast][Info] Showing: '{title}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                // Play notification sound for legacy info toasts
                _ = Task.Run(async () =>
                {
                    try
                    {
                        if (iconText == "\u26A0" || iconText == "\u274C") // Warning or error icon
                        {
                            await Zer0Talk.Services.AudioHelper.PlayAlertNotificationAsync();
                        }
                        else
                        {
                            await Zer0Talk.Services.AudioHelper.PlayNotificationAsync();
                        }
                    }
                    catch (Exception ex)
                    {
                        try { WriteUiLog($"[Toast][Info] Audio notification failed: {ex.Message}"); } catch { }
                    }
                });
                
                var contentPanel = new StackPanel { Spacing = 6 };
                
                // Add title with optional icon
                var titlePanel = new StackPanel 
                { 
                    Orientation = Avalonia.Layout.Orientation.Horizontal, 
                    Spacing = 8 
                };
                
                if (!string.IsNullOrEmpty(iconText))
                {
                    titlePanel.Children.Add(new TextBlock 
                    { 
                        Text = iconText, 
                        FontSize = 16,
                        FontStyle = Avalonia.Media.FontStyle.Normal,
                        FontWeight = Avalonia.Media.FontWeight.Normal,
                        Foreground = new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.FromRgb(255, 165, 0)),
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                        RenderTransform = null // Ensure no transforms are applied
                    });
                }
                
                titlePanel.Children.Add(new TextBlock 
                { 
                    Text = title, 
                    FontWeight = Avalonia.Media.FontWeight.SemiBold,
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                });
                
                contentPanel.Children.Add(titlePanel);
                contentPanel.Children.Add(new TextBlock 
                { 
                    Text = message, 
                    TextWrapping = Avalonia.Media.TextWrapping.Wrap, 
                    MaxWidth = 360 
                });
                
                var border = new Border
                {
                    Padding = new Thickness(12),
                    CornerRadius = new CornerRadius(8),
                    Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Surface"),
                    BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border"),
                    BorderThickness = new Thickness(1),
                    Child = contentPanel
                };

                var toast = new Window
                {
                    CanResize = false,
                    Width = 420,
                    Height = 120,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = null,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    IsHitTestVisible = false,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 32
                };

                try
                {
                    // Position near top-right of owner
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)sz.Width - 440, Math.Max(0, p.Y + 56));
                }
                catch { }

                // Show non-modally, then auto-dismiss
                toast.Show(owner);
                try { await Task.Delay(dismissAfterMs); } catch { }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][Info] Closed: '{title}'"); } catch { }
            });
        }



        // Success info popup with check icon
        public async Task ShowSuccessAsync(string title, string message, int dismissAfterMs = 2500)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Success);
        }

        // Warning info popup with caution icon
        public async Task ShowWarningAsync(string title, string message, int dismissAfterMs = 3000)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Warning);
        }

        // Error info popup with error icon
        public async Task ShowErrorAsync(string title, string message, int dismissAfterMs = 4000)
        {
            await ShowEnhancedToastAsync(title, message, dismissAfterMs, ToastType.Error);
        }

        // Enhanced toast with animations, progress, and better styling
        public async Task ShowEnhancedToastAsync(string title, string message, int dismissAfterMs, ToastType type)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
                try { WriteUiLog($"[Toast][{type}] Showing: '{title}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                // Play appropriate sound for toast type
                _ = Task.Run(async () =>
                {
                    try
                    {
                        if (type == ToastType.Warning || type == ToastType.Error)
                        {
                            await Zer0Talk.Services.AudioHelper.PlayAlertNotificationAsync();
                        }
                        else
                        {
                            await Zer0Talk.Services.AudioHelper.PlayNotificationAsync();
                        }
                    }
                    catch (Exception ex)
                    {
                        try { WriteUiLog($"[Toast][{type}] Audio notification failed: {ex.Message}"); } catch { }
                    }
                });
                
                // Get type-specific styling
                var (iconText, accentColor, bgColor) = GetToastStyling(type);
                
                var contentPanel = new StackPanel { Spacing = 8 };
                
                // Header with icon and title
                var headerPanel = new StackPanel 
                { 
                    Orientation = Avalonia.Layout.Orientation.Horizontal, 
                    Spacing = 10 
                };
                
                // Icon
                var iconBlock = new TextBlock
                {
                    Text = iconText,
                    FontSize = 18,
                    FontStyle = Avalonia.Media.FontStyle.Normal,
                    FontWeight = Avalonia.Media.FontWeight.Normal,
                    Foreground = new Avalonia.Media.SolidColorBrush(accentColor),
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                    RenderTransform = null
                };
                headerPanel.Children.Add(iconBlock);
                
                // Title
                var titleBlock = new TextBlock
                {
                    Text = title,
                    FontWeight = Avalonia.Media.FontWeight.SemiBold,
                    FontSize = 14,
                    VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center,
                    Foreground = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.PrimaryText")
                };
                headerPanel.Children.Add(titleBlock);
                
                contentPanel.Children.Add(headerPanel);
                
                // Message
                if (!string.IsNullOrWhiteSpace(message))
                {
                    var messageBlock = new TextBlock
                    {
                        Text = message,
                        TextWrapping = Avalonia.Media.TextWrapping.Wrap,
                        MaxWidth = 340,
                        FontSize = 13,
                        Opacity = 0.9,
                        Margin = new Thickness(28, 0, 0, 0), // Indent under icon
                        Foreground = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.SecondaryText")
                    };
                    contentPanel.Children.Add(messageBlock);
                }
                
                // Progress bar
                var progressBar = new Avalonia.Controls.ProgressBar
                {
                    Height = 3,
                    Margin = new Thickness(0, 4, 0, 0),
                    Background = new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.FromArgb(30, 255, 255, 255)),
                    Foreground = new Avalonia.Media.SolidColorBrush(accentColor),
                    Value = 100,
                    Minimum = 0,
                    Maximum = 100
                };
                contentPanel.Children.Add(progressBar);
                
                // Enhanced border with accent and shadow effect
                var border = new Border
                {
                    Padding = new Thickness(16, 12),
                    CornerRadius = new CornerRadius(10),
                    Background = new Avalonia.Media.SolidColorBrush(bgColor),
                    BorderBrush = new Avalonia.Media.SolidColorBrush(accentColor),
                    BorderThickness = new Thickness(0, 0, 0, 3), // Bottom accent line
                    Child = contentPanel,
                    BoxShadow = new Avalonia.Media.BoxShadows(new Avalonia.Media.BoxShadow
                    {
                        Color = Avalonia.Media.Color.FromArgb(40, 0, 0, 0),
                        Blur = 12,
                        OffsetY = 4,
                        OffsetX = 2
                    })
                };
                
                var toast = new Window
                {
                    CanResize = false,
                    SizeToContent = SizeToContent.WidthAndHeight,
                    MinWidth = 300,
                    MaxWidth = 450,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = Avalonia.Media.Brushes.Transparent,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 0
                };
                
                // Click to dismiss
                border.PointerPressed += (_, __) => 
                {
                    try { toast.Close(); } catch { }
                };
                border.Cursor = new Avalonia.Input.Cursor(Avalonia.Input.StandardCursorType.Hand);
                
                // Position in top-right with offset for multiple toasts
                try
                {
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)sz.Width - 470, Math.Max(0, p.Y + 60));
                }
                catch { }
                
                // Smooth fade-in effect
                border.Opacity = 0.2;
                toast.Show(owner);
                
                // Animate opacity from 0.2 to 1.0
                for (int i = 0; i <= 12; i++)
                {
                    border.Opacity = 0.2 + (i * 0.067); // 0.2 to 1.0 in 12 steps
                    await Task.Delay(15); // 180ms total
                }
                
                // Animate progress bar
                var progressAnimation = new System.Threading.CancellationTokenSource();
                _ = Task.Run(async () =>
                {
                    var startTime = DateTime.UtcNow;
                    var duration = dismissAfterMs;
                    
                    while (!progressAnimation.Token.IsCancellationRequested)
                    {
                        var elapsed = (DateTime.UtcNow - startTime).TotalMilliseconds;
                        var remaining = Math.Max(0, duration - elapsed);
                        var progress = Math.Max(0, (remaining / duration) * 100);
                        
                        await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(() =>
                        {
                            try { progressBar.Value = progress; } catch { }
                        });
                        
                        if (remaining <= 0) break;
                        await Task.Delay(50, progressAnimation.Token);
                    }
                }, progressAnimation.Token);
                
                // Auto-dismiss
                try { await Task.Delay(dismissAfterMs); } catch { }
                
                progressAnimation.Cancel();
                
                // Smooth fade-out effect
                for (int i = 10; i >= 0; i--)
                {
                    border.Opacity = i * 0.1; // 1.0 to 0.0 in 11 steps
                    await Task.Delay(20); // 220ms total
                }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][{type}] Closed: '{title}'"); } catch { }
            });
        }
        
        private static (string icon, Avalonia.Media.Color accent, Avalonia.Media.Color bg) GetToastStyling(ToastType type)
        {
            return type switch
            {
                ToastType.Success => ("\u2713", Avalonia.Media.Color.FromRgb(34, 197, 94), Avalonia.Media.Color.FromRgb(240, 253, 244)),   // ✓ Green
                ToastType.Warning => ("\u26A0", Avalonia.Media.Color.FromRgb(245, 158, 11), Avalonia.Media.Color.FromRgb(255, 251, 235)),  // ⚠ Amber
                ToastType.Error => ("\u274C", Avalonia.Media.Color.FromRgb(239, 68, 68), Avalonia.Media.Color.FromRgb(254, 242, 242)),     // ❌ Red
                _ => ("\u2139", Avalonia.Media.Color.FromRgb(59, 130, 246), Avalonia.Media.Color.FromRgb(239, 246, 255))                 // ℹ Blue
            };
        }

        // Centered toast for chat area notifications
        public async Task ShowCenteredToastAsync(string message, int dismissAfterMs = 1500)
        {
            var lifetime = Avalonia.Application.Current?.ApplicationLifetime as IClassicDesktopStyleApplicationLifetime;
            if (lifetime?.MainWindow is not Window owner) return;

            await Avalonia.Threading.Dispatcher.UIThread.InvokeAsync(async () =>
            {
                try { WriteUiLog($"[Toast][Centered] Showing: '{message}' - will auto-dismiss in {dismissAfterMs}ms"); } catch { }
                
                var border = new Border
                {
                    Padding = new Thickness(16, 8),
                    CornerRadius = new CornerRadius(6),
                    Background = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Surface"),
                    BorderBrush = (Avalonia.Media.IBrush?)Application.Current?.FindResource("App.Border"),
                    BorderThickness = new Thickness(1),
                    Child = new TextBlock 
                    { 
                        Text = message, 
                        FontWeight = Avalonia.Media.FontWeight.Medium,
                        HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Center
                    }
                };

                var toast = new Window
                {
                    CanResize = false,
                    Width = 200,
                    Height = 50,
                    ShowInTaskbar = false,
                    ShowActivated = false,
                    SystemDecorations = SystemDecorations.None,
                    Background = null,
                    Content = border,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Topmost = true,
                    IsHitTestVisible = false,
                    ExtendClientAreaToDecorationsHint = true,
                    ExtendClientAreaChromeHints = Avalonia.Platform.ExtendClientAreaChromeHints.NoChrome,
                    ExtendClientAreaTitleBarHeightHint = 32
                };

                try
                {
                    // Position in top-center of owner window
                    var p = owner.Position;
                    var sz = owner.Bounds;
                    toast.Position = new PixelPoint(p.X + (int)(sz.Width - 200) / 2, p.Y + 120);
                }
                catch { }

                // Show non-modally, then auto-dismiss
                toast.Show(owner);
                try { await Task.Delay(dismissAfterMs); } catch { }
                try { toast.Close(); } catch { }
                try { WriteUiLog($"[Toast][Centered] Closed: '{message}'"); } catch { }
            });

        }

    }
}
